# Generated by Django 5.0.3 on 2024-05-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_alter_job_options_alter_job_commission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-status', 'created_on']},
        ),
    ]
