# Generated by Django 5.0.3 on 2024-05-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0008_commission_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicant',
        ),
        migrations.DeleteModel(
            name='Commission',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
