# Generated by Django 5.0.3 on 2024-05-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0014_jobapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-status', 'created_on']},
        ),
    ]
