# Generated by Django 5.0.3 on 2024-05-14 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0015_alter_commission_options'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='user_management.profile'),
            preserve_default=False,
        ),
    ]
