# Generated by Django 5.0.3 on 2024-05-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0010_alter_commission_owner'),
        ('commissions', '0019_alter_commission_owner'),
    ]

    operations = [
    ]
